### ISSUE TITLE
GraphQL error: 'str' object has no attribute 'decode' 

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#496]
This error is raised by the mutation `tokenAuth`. For example, after running the next mutation:
```
mutation tokenAuth {
  tokenAuth(username:"root", password:"*****") {
  	token
  }
}
```

I get the next error:
```
{
  "errors": [
    {
      "message": "'str' object has no attribute 'decode'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "tokenAuth"
      ],
      "extensions": {
        "code": 128
      }
    }
  ],
  "data": {
    "tokenAuth": null
  }
}
```

**Comment by sduenas** [comment]
After some debugging, I was able to catch the exception:

```
Traceback (most recent call last):
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql_jwt/middleware.py", line 81, in resolve
    return next(root, info, **kwargs)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/promise/promise.py", line 759, in wrapper
    return cls(executor)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/promise/promise.py", line 146, in __init__
    self._resolve_from_executor(executor)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/promise/promise.py", line 493, in _resolve_from_executor
    raise e
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/promise/promise.py", line 489, in _resolve_from_executor
    executor(resolve, reject)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/promise/promise.py", line 757, in executor
    return resolve(f(*args, **kwargs))
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql_jwt/decorators.py", line 140, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql_jwt/decorators.py", line 129, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql_jwt/decorators.py", line 121, in wrapper
    result = f(cls, *args, **kwargs)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql_jwt/decorators.py", line 107, in wrapper
    return maybe_thenable((context, user, result), on_token_auth_resolve)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphene/utils/thenables.py", line 42, in maybe_thenable
    return on_resolve(obj)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql_jwt/decorators.py", line 70, in on_token_auth_resolve
    payload.token = jwt_settings.JWT_ENCODE_HANDLER(payload.payload, context)
  File "/home/sduenas/.cache/pypoetry/virtualenvs/sortinghat-SE9DHfbA-py3.8/lib/python3.8/site-packages/graphql_jwt/utils.py", line 37, in jwt_encode
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by sduenas** [comment]
The previous error is caused by `django-graphql-jwt` which is incompatible with PyJWT 2.0. `PyJWT` package is set in `poetry.lock` to version `2.0.1` because `django-graphql-jwt` says it works with `versions >1.5.0`. This is not supported as mentioned in https://github.com/flavors/django-graphql-jwt/issues/242.

We need to pin PyJWT to a different version compatible with the later.

**Comment by sduenas** [comment]
Fixed by #497.
